# -*- coding: utf-8 -*-
"""python oop(class / construtor)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qSZLKs8uO_2C4IwMRXyO9B37IOZ2Uep

# OOP
- class
- _init_ - constructor
"""

class Main:
  def say(self):
    print("hellow")


main=Main()
main.say()

class Main:
  def say(self,name):
    print("hellow ",name)


main=Main()
main.say("piyumal")

class Main:
  def say(self,name):
    print("hellow ",name)


main=Main()
main.say("piyumal")

main=Main()
main.say("Nipuna")

class Main:
  def say(self,name):
    x=name
    print("hellow ",x)


main=Main()
main.say("piyumal")

print("name is ",main.x)  #wrong

class Main:
  def say(self,name):
    x=name
    print("hellow ",x)


main=Main()
main.say("piyumal")

print("name is ",main.self.x)

class Main:
  def say(self,name):
    self.x=name
    print("hellow ",self.x)



main=Main()
main.say("nipuna")


main.x="chamara"
print("name is ",main.x)

"""---
- init funtion
---
"""

class Student():
  def __init__(self):   # java vala constructor eka vagemai (object hadana velavedi call venava.)
    print("hellow")

st1=Student()

class Student():
  def __init__(self,name,age):   # java vala constructor eka vagemai (object hadana velavedi call venava.)
    self.name=name
    self.age=age

st1=Student("piyumal",23)
st2=Student("nipuna",24)

print("Name is ",st1.name," and age ",st1.age)
print("Name is ",st2.name," and age ",st2.age)