# -*- coding: utf-8 -*-
"""python function

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qSZLKs8uO_2C4IwMRXyO9B37IOZ2Uep

## function

- pow
- help
- max
- min
- sqrt

---

- upper
- capitalize
- lower

---
- replace
- split
"""

dir(__builtin__)

print(pow(4,2))  #4*4=16

print(help(pow)) #pow(base, exp, mod=None)

print(pow(4,2)) #pow(base, exp, mod=None)

print(max(3,1,5,7,4)) #max=7

print(min(3,1,5,7,4)) # min=1

import datetime
import math

#module is funtion kipayaka ekathuvak
print(math.sqrt(64))

import datetime
import math

# date time module
print(datetime.datetime.now())

x="piyumal"
print(x.capitalize())  #first latter capital

print(x.upper())  #all latter capital

print(x.lower())  #all latter simple

x="piyumal"
print(x[2])

x="piyumal"
print(x[2:6])

x="piyumal"
print(x[2:])

x="pikumal"
print(x.replace('k','y'))

x="piyumal"
print(x.split('u'))

