# -*- coding: utf-8 -*-
"""python data_type

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qSZLKs8uO_2C4IwMRXyO9B37IOZ2Uep

## data type

- integer
- floal
- boolean
- complex
- string

---

- list
- set
- tuple
- dictionnary
"""

x=10  #integer
print(x)
print(type(x))

y=20.5  #floal
print(y)
print(type(y))

a=True  #boolean
print(a)
print(type(a))

b="piyumal"  #string
print(b)
print(type(b))

c=2+3j  #complex
print(c)
print(type(c))

d=["kamal","namal","saman"]  #list
print(d)
print(type(d))

my_dict = {}
my_dict['Name']="piyumal"
my_dict['add']="galle"
print(my_dict)
print(type(my_dict))

k=10
name="piyumal"
print("my age is ",str(k) , " my name is "+name)
print("my age is "+str(k) + " my name is "+name)
print("my age is %s my name is %s" %(k,name))

"""---
#  * input values
---
"""

age = input("enter your age : ")
print(age)
print(type(age))

age = int(input("enter your age : "))  # convert to integer values
print(age)
print(type(age))

age = float(input("enter your age : "))  # convert to float values
print(age)
print(type(age))